name = "latewiz-modified"
main = ".vercel/output/static/_worker.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".vercel/output/static"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "latewiz-modified"
